server:
  port: 8081

spring:
  application:
    name: customer-service
  
  datasource:
    url: jdbc:h2:mem:customer_db
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

# JWT Configuration
jwt:
  secret: bank-microservices-shared-jwt-secret-2024
  expiration: 86400000

logging:
  level:
    com.bank.customer: INFO